import type { Project } from "@prisma/client";

export function ProjectVisual({ project }: { project: Project }) {
  if (project.visualType === "video" && project.videoUrl) {
    return <div className="screen media-screen"><video src={project.videoUrl} autoPlay muted loop playsInline controls preload="metadata" /></div>;
  }
  if (project.visualType === "image" && project.imageUrl) {
    return <div className="screen media-screen"><img src={project.imageUrl} alt={project.title} /></div>;
  }

  return <div className="screen"><div className="screenbar"><span className="dot"></span><span className="dot"></span><span className="dot"></span><span className="screen-title">portfolio_preview</span></div><div className="ui">
    {project.animation === "pipeline" && <div className="ui-grid"><div className="panel"><div className="mini-head"><strong>Partner pipeline</strong><span className="pulse"></span></div><div className="mini-line"></div><div className="mini-line"></div><div className="mini-line"></div><div className="mini-line"></div><div className="bars-row"><span style={{height:"35px"}}></span><span style={{height:"50px"}}></span><span style={{height:"68px"}}></span><span style={{height:"52px"}}></span><span style={{height:"78px"}}></span><span style={{height:"65px"}}></span><span style={{height:"88px"}}></span></div></div><div className="panel"><small>Activation</small><div className="big-number">84%</div><small>qualified → active</small><div className="progress"><div style={{width:"84%"}}></div></div></div></div>}
    {project.animation === "metrics" && <><div className="hero-mini"><div className="metric-box"><span>Revenue</span><strong>$12.4K</strong><span>+32.4% this cycle</span></div><div className="metric-box"><span>Creators</span><strong>42</strong><span>active partners</span></div></div><div className="panel chart-panel"><small>Performance</small><div className="bars-row"><span style={{height:"32px"}}></span><span style={{height:"48px"}}></span><span style={{height:"74px"}}></span><span style={{height:"55px"}}></span><span style={{height:"90px"}}></span><span style={{height:"66px"}}></span><span style={{height:"84px"}}></span><span style={{height:"58px"}}></span></div></div></>}
    {project.animation === "app" && <div className="app-preview"><div className="app-sidebar"><span></span><span></span><span></span><span></span></div><div className="app-main"><div className="app-nav"></div><div className="app-cards"><div></div><div></div><div></div></div><div className="app-block"></div></div></div>}
    {project.animation === "flow" && <div className="flow"><div className="node">Landing</div><div className="arrow">→</div><div className="node">Form</div><div className="arrow">→</div><div className="node">Thank You</div><div className="arrow">→</div><div className="node">Offer</div><div className="flow-note">Conversion event: lead_created ✓</div></div>}
    {project.animation === "chat" && <div className="chat"><div className="bubble">New lead captured → scoring started</div><div className="bubble me">Score passed threshold → outreach queued</div><div className="bubble">Email sent → waiting for response</div><div className="bubble me">Reply detected → notify operator</div><span className="workflow-status"><span className="pulse"></span> workflow active</span></div>}
    {project.animation === "qualifier" && <div className="panel"><div className="mini-head"><strong>Prospect #184</strong><span className="qualified">Qualified</span></div><hr/><div className="mini-line"></div><div className="mini-line"></div><div className="mini-line"></div><div className="qualifier-grid"><div><small>Niche match</small><b>92%</b></div><div><small>Contact quality</small><b>Verified</b></div></div></div>}
    {project.animation === "audit" && <><div className="lock"><div className="pulse"></div><strong>Controlled stabilization</strong><span>State visibility · run locking · retry recovery · acceptance tests</span></div><div className="audit-grid"><div className="metric-box"><strong>✓</strong><span>Verified</span></div><div className="metric-box"><strong>↗</strong><span>Recommended</span></div><div className="metric-box"><strong>?</strong><span>Validate</span></div></div></>}
    {!['pipeline','metrics','app','flow','chat','qualifier','audit'].includes(project.animation) && <div className="lock"><div className="pulse"></div><strong>Animated showcase</strong><span>Edit this animation type from the dashboard.</span></div>}
  </div></div>;
}
